"""empty message

Revision ID: 469ec65149e4
Revises: 2c035b51b708
Create Date: 2023-10-03 19:23:07.720875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469ec65149e4'
down_revision = '2c035b51b708'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
